-- ============================================================
-- Phase 5: Alerts
-- Automated monitoring for vibration/temperature alarms and
-- sustained threshold breaches. Logs to ALERT_LOG table.
-- ============================================================

USE WAREHOUSE PREDICT_MAINT_WH;
USE SCHEMA PREDICT_MAINT_DB.ANALYTICS;

-- Alert log table for audit trail
CREATE TABLE IF NOT EXISTS ALERT_LOG (
    ALERT_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ALERT_NAME      VARCHAR(100)  NOT NULL,
    ASSET_ID        VARCHAR(10)   NOT NULL,
    ALERT_TYPE      VARCHAR(20)   NOT NULL,
    SENSOR_VALUE    FLOAT,
    THRESHOLD_VALUE FLOAT,
    MESSAGE         VARCHAR(500)
);

-- Alert 1: Vibration ALARM (any asset exceeds alarm threshold)
CREATE OR REPLACE ALERT PDM_VIB_ALARM_ALERT
  WAREHOUSE = PREDICT_MAINT_WH
  SCHEDULE = '30 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM ASSET_HEALTH_SUMMARY WHERE VIB_STATUS = 'ALARM'
  ))
  THEN
    INSERT INTO ALERT_LOG (ALERT_NAME, ASSET_ID, ALERT_TYPE, SENSOR_VALUE, THRESHOLD_VALUE, MESSAGE)
    SELECT 'PDM_VIB_ALARM_ALERT', h.ASSET_ID, 'VIB_ALARM',
           h.LATEST_VIBRATION, a.VIB_ALARM_MM_S,
           'Vibration ALARM on ' || h.ASSET_ID || ' (' || h.ASSET_TYPE || ', ' || h.PLANT || '): ' ||
           ROUND(h.LATEST_VIBRATION, 2) || ' mm/s exceeds alarm threshold ' || a.VIB_ALARM_MM_S || ' mm/s'
    FROM ASSET_HEALTH_SUMMARY h
    JOIN PREDICT_MAINT_DB.RAW.ASSETS a ON h.ASSET_ID = a.ASSET_ID
    WHERE h.VIB_STATUS = 'ALARM';

-- Alert 2: Temperature ALARM
CREATE OR REPLACE ALERT PDM_TEMP_ALARM_ALERT
  WAREHOUSE = PREDICT_MAINT_WH
  SCHEDULE = '30 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM ASSET_HEALTH_SUMMARY WHERE TEMP_STATUS = 'ALARM'
  ))
  THEN
    INSERT INTO ALERT_LOG (ALERT_NAME, ASSET_ID, ALERT_TYPE, SENSOR_VALUE, THRESHOLD_VALUE, MESSAGE)
    SELECT 'PDM_TEMP_ALARM_ALERT', h.ASSET_ID, 'TEMP_ALARM',
           h.LATEST_TEMPERATURE, a.TEMP_ALARM_C,
           'Temperature ALARM on ' || h.ASSET_ID || ' (' || h.ASSET_TYPE || ', ' || h.PLANT || '): ' ||
           ROUND(h.LATEST_TEMPERATURE, 1) || ' C exceeds alarm threshold ' || a.TEMP_ALARM_C || ' C'
    FROM ASSET_HEALTH_SUMMARY h
    JOIN PREDICT_MAINT_DB.RAW.ASSETS a ON h.ASSET_ID = a.ASSET_ID
    WHERE h.TEMP_STATUS = 'ALARM';

-- Alert 3: Sustained breaches (>=10 in 24h, indicates degradation in progress)
CREATE OR REPLACE ALERT PDM_SUSTAINED_BREACH_ALERT
  WAREHOUSE = PREDICT_MAINT_WH
  SCHEDULE = '30 MINUTE'
  IF (EXISTS (
    SELECT 1 FROM ASSET_HEALTH_SUMMARY
    WHERE VIB_BREACH_COUNT_24H >= 10 OR TEMP_BREACH_COUNT_24H >= 10
  ))
  THEN
    INSERT INTO ALERT_LOG (ALERT_NAME, ASSET_ID, ALERT_TYPE, SENSOR_VALUE, MESSAGE)
    SELECT 'PDM_SUSTAINED_BREACH_ALERT', ASSET_ID, 'SUSTAINED_BREACH',
           GREATEST(VIB_BREACH_COUNT_24H, TEMP_BREACH_COUNT_24H),
           'Sustained threshold breaches on ' || ASSET_ID || ': ' ||
           VIB_BREACH_COUNT_24H || ' vibration + ' || TEMP_BREACH_COUNT_24H || ' temperature breaches in 24h'
    FROM ASSET_HEALTH_SUMMARY
    WHERE VIB_BREACH_COUNT_24H >= 10 OR TEMP_BREACH_COUNT_24H >= 10;

-- Resume all alerts
ALTER ALERT PDM_VIB_ALARM_ALERT RESUME;
ALTER ALERT PDM_TEMP_ALARM_ALERT RESUME;
ALTER ALERT PDM_SUSTAINED_BREACH_ALERT RESUME;

-- Verify alerts are active
SHOW ALERTS IN SCHEMA PREDICT_MAINT_DB.ANALYTICS;

-- Query alert history
SELECT * FROM ALERT_LOG ORDER BY ALERT_TS DESC LIMIT 20;
