-- ============================================================
-- Phase 2: Feature Engineering - ASSET_SENSOR_STATS
-- Core ML feature table with rolling statistics, rate-of-change,
-- baseline deviation, and threshold breach detection
-- Dynamic Table | Incremental | 30-min lag | 172,800 rows
-- ============================================================

USE WAREHOUSE PREDICT_MAINT_WH;
USE SCHEMA PREDICT_MAINT_DB.ANALYTICS;

CREATE OR REPLACE DYNAMIC TABLE ASSET_SENSOR_STATS
    TARGET_LAG = '30 minutes'
    WAREHOUSE = PREDICT_MAINT_WH
    AS
WITH sensor_with_baseline AS (
    SELECT
        s.READING_TS,
        s.ASSET_ID,
        a.ASSET_TYPE,
        a.PLANT,
        a.CRITICALITY,
        s.VIBRATION_MM_S,
        s.TEMPERATURE_C,
        s.RPM,
        s.MOTOR_CURRENT_A,
        a.BASELINE_VIBRATION_MM_S,
        a.BASELINE_TEMP_C,
        a.BASELINE_CURRENT_A,
        a.RATED_RPM,
        a.VIB_ALERT_MM_S,
        a.VIB_ALARM_MM_S,
        a.TEMP_ALERT_C,
        a.TEMP_ALARM_C,
        CASE WHEN s.VIBRATION_MM_S IS NULL OR s.TEMPERATURE_C IS NULL
              OR s.RPM IS NULL OR s.MOTOR_CURRENT_A IS NULL
             THEN 1 ELSE 0 END AS SENSOR_DROPOUT_FLAG
    FROM PREDICT_MAINT_DB.RAW.SENSOR_READINGS s
    JOIN PREDICT_MAINT_DB.RAW.ASSETS a ON s.ASSET_ID = a.ASSET_ID
)
SELECT
    READING_TS,
    ASSET_ID,
    ASSET_TYPE,
    PLANT,
    CRITICALITY,
    VIBRATION_MM_S,
    TEMPERATURE_C,
    RPM,
    MOTOR_CURRENT_A,
    SENSOR_DROPOUT_FLAG,

    -- === ROLLING MEANS (1h=2, 6h=12, 24h=48, 7d=336 readings) ===
    AVG(VIBRATION_MM_S)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)   AS VIB_AVG_1H,
    AVG(VIBRATION_MM_S)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS VIB_AVG_6H,
    AVG(VIBRATION_MM_S)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS VIB_AVG_24H,
    AVG(VIBRATION_MM_S)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 335 PRECEDING AND CURRENT ROW) AS VIB_AVG_7D,

    AVG(TEMPERATURE_C)    OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)   AS TEMP_AVG_1H,
    AVG(TEMPERATURE_C)    OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS TEMP_AVG_6H,
    AVG(TEMPERATURE_C)    OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS TEMP_AVG_24H,
    AVG(TEMPERATURE_C)    OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 335 PRECEDING AND CURRENT ROW) AS TEMP_AVG_7D,

    AVG(MOTOR_CURRENT_A)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)   AS CURR_AVG_1H,
    AVG(MOTOR_CURRENT_A)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS CURR_AVG_6H,
    AVG(MOTOR_CURRENT_A)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS CURR_AVG_24H,
    AVG(MOTOR_CURRENT_A)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 335 PRECEDING AND CURRENT ROW) AS CURR_AVG_7D,

    -- === ROLLING STD DEV (6h, 24h) ===
    STDDEV(VIBRATION_MM_S)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS VIB_STD_6H,
    STDDEV(VIBRATION_MM_S)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS VIB_STD_24H,
    STDDEV(TEMPERATURE_C)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS TEMP_STD_6H,
    STDDEV(TEMPERATURE_C)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS TEMP_STD_24H,
    STDDEV(MOTOR_CURRENT_A) OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 11 PRECEDING AND CURRENT ROW)  AS CURR_STD_6H,
    STDDEV(MOTOR_CURRENT_A) OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW)  AS CURR_STD_24H,

    -- === RATE OF CHANGE (current vs 1h ago and 6h ago) ===
    VIBRATION_MM_S  - LAG(VIBRATION_MM_S, 2)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS VIB_DELTA_1H,
    VIBRATION_MM_S  - LAG(VIBRATION_MM_S, 12) OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS VIB_DELTA_6H,
    TEMPERATURE_C   - LAG(TEMPERATURE_C, 2)   OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS TEMP_DELTA_1H,
    TEMPERATURE_C   - LAG(TEMPERATURE_C, 12)  OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS TEMP_DELTA_6H,
    MOTOR_CURRENT_A - LAG(MOTOR_CURRENT_A, 2) OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS CURR_DELTA_1H,
    MOTOR_CURRENT_A - LAG(MOTOR_CURRENT_A, 12) OVER (PARTITION BY ASSET_ID ORDER BY READING_TS) AS CURR_DELTA_6H,

    -- === BASELINE DEVIATION (%) ===
    CASE WHEN BASELINE_VIBRATION_MM_S > 0
         THEN (VIBRATION_MM_S - BASELINE_VIBRATION_MM_S) / BASELINE_VIBRATION_MM_S
         ELSE NULL END AS VIB_BASELINE_DEV_PCT,
    CASE WHEN BASELINE_TEMP_C > 0
         THEN (TEMPERATURE_C - BASELINE_TEMP_C) / BASELINE_TEMP_C
         ELSE NULL END AS TEMP_BASELINE_DEV_PCT,
    CASE WHEN BASELINE_CURRENT_A > 0
         THEN (MOTOR_CURRENT_A - BASELINE_CURRENT_A) / BASELINE_CURRENT_A
         ELSE NULL END AS CURR_BASELINE_DEV_PCT,

    -- === THRESHOLD BREACH FLAGS ===
    CASE WHEN VIBRATION_MM_S >= VIB_ALARM_MM_S THEN 'ALARM'
         WHEN VIBRATION_MM_S >= VIB_ALERT_MM_S THEN 'ALERT'
         ELSE 'NORMAL' END AS VIB_STATUS,
    CASE WHEN TEMPERATURE_C >= TEMP_ALARM_C THEN 'ALARM'
         WHEN TEMPERATURE_C >= TEMP_ALERT_C THEN 'ALERT'
         ELSE 'NORMAL' END AS TEMP_STATUS,

    -- === TRAILING 24H BREACH COUNTS ===
    SUM(CASE WHEN VIBRATION_MM_S >= VIB_ALERT_MM_S THEN 1 ELSE 0 END)
        OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW) AS VIB_BREACH_COUNT_24H,
    SUM(CASE WHEN TEMPERATURE_C >= TEMP_ALERT_C THEN 1 ELSE 0 END)
        OVER (PARTITION BY ASSET_ID ORDER BY READING_TS ROWS BETWEEN 47 PRECEDING AND CURRENT ROW) AS TEMP_BREACH_COUNT_24H

FROM sensor_with_baseline;
