-- ============================================================
-- Phase 3: Model Registry & Inference
-- Register the trained model and run batch inference
-- Prerequisite: Run train_model.py first to train and register the model
-- ============================================================

USE WAREHOUSE PREDICT_MAINT_WH;
USE SCHEMA PREDICT_MAINT_DB.ANALYTICS;

-- 1. Verify model is registered
SHOW MODELS IN SCHEMA PREDICT_MAINT_DB.ANALYTICS;

-- 2. Describe model version
DESCRIBE MODEL PREDICT_MAINT_FAILURE_DETECTOR;

-- 3. Run batch inference on latest 48h of sensor data per asset
-- This scores every recent reading with a failure probability
WITH recent_readings AS (
    SELECT *
    FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_SENSOR_STATS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY READING_TS DESC) <= 96
)
SELECT
    ASSET_ID,
    READING_TS,
    PREDICT_MAINT_FAILURE_DETECTOR!PREDICT(
        VIBRATION_MM_S, TEMPERATURE_C, RPM, MOTOR_CURRENT_A,
        VIB_AVG_1H, VIB_AVG_6H, VIB_AVG_24H, VIB_AVG_7D,
        TEMP_AVG_1H, TEMP_AVG_6H, TEMP_AVG_24H, TEMP_AVG_7D,
        CURR_AVG_1H, CURR_AVG_6H, CURR_AVG_24H, CURR_AVG_7D,
        VIB_STD_6H, VIB_STD_24H, TEMP_STD_6H, TEMP_STD_24H,
        CURR_STD_6H, CURR_STD_24H,
        VIB_DELTA_1H, VIB_DELTA_6H, TEMP_DELTA_1H, TEMP_DELTA_6H,
        CURR_DELTA_1H, CURR_DELTA_6H,
        VIB_BASELINE_DEV_PCT, TEMP_BASELINE_DEV_PCT, CURR_BASELINE_DEV_PCT,
        VIB_BREACH_COUNT_24H, TEMP_BREACH_COUNT_24H, SENSOR_DROPOUT_FLAG
    ) AS PREDICTION
FROM recent_readings
ORDER BY ASSET_ID, READING_TS DESC;

-- 4. Asset-level risk summary (latest readings scored)
-- Aggregates predictions into a per-asset risk score
WITH scored AS (
    SELECT
        s.*,
        PREDICT_MAINT_FAILURE_DETECTOR!PREDICT(
            VIBRATION_MM_S, TEMPERATURE_C, RPM, MOTOR_CURRENT_A,
            VIB_AVG_1H, VIB_AVG_6H, VIB_AVG_24H, VIB_AVG_7D,
            TEMP_AVG_1H, TEMP_AVG_6H, TEMP_AVG_24H, TEMP_AVG_7D,
            CURR_AVG_1H, CURR_AVG_6H, CURR_AVG_24H, CURR_AVG_7D,
            VIB_STD_6H, VIB_STD_24H, TEMP_STD_6H, TEMP_STD_24H,
            CURR_STD_6H, CURR_STD_24H,
            VIB_DELTA_1H, VIB_DELTA_6H, TEMP_DELTA_1H, TEMP_DELTA_6H,
            CURR_DELTA_1H, CURR_DELTA_6H,
            VIB_BASELINE_DEV_PCT, TEMP_BASELINE_DEV_PCT, CURR_BASELINE_DEV_PCT,
            VIB_BREACH_COUNT_24H, TEMP_BREACH_COUNT_24H, SENSOR_DROPOUT_FLAG
        ) AS PREDICTION
    FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_SENSOR_STATS s
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY READING_TS DESC) <= 48
)
SELECT
    ASSET_ID,
    ASSET_TYPE,
    PLANT,
    CRITICALITY,
    MAX(READING_TS) AS LATEST_TS,
    COUNT(*) AS READINGS_SCORED,
    SUM(CASE WHEN PREDICTION:label::INT = 1 THEN 1 ELSE 0 END) AS FLAGGED_READINGS,
    CASE
        WHEN SUM(CASE WHEN PREDICTION:label::INT = 1 THEN 1 ELSE 0 END) >= 24 THEN 'HIGH RISK'
        WHEN SUM(CASE WHEN PREDICTION:label::INT = 1 THEN 1 ELSE 0 END) >= 6 THEN 'ELEVATED'
        ELSE 'NORMAL'
    END AS RISK_LEVEL
FROM scored
GROUP BY ASSET_ID, ASSET_TYPE, PLANT, CRITICALITY
ORDER BY FLAGGED_READINGS DESC;
