-- ============================================================
-- Phase 2: Validation Queries
-- Run after creating all Phase 2 objects to verify correctness
-- ============================================================

USE WAREHOUSE PREDICT_MAINT_WH;

-- 1. Row counts for all analytics objects
SELECT 'ASSET_SENSOR_STATS'    AS OBJECT, COUNT(*) AS ROWS FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_SENSOR_STATS
UNION ALL SELECT 'PRODUCTION_OEE',         COUNT(*) FROM PREDICT_MAINT_DB.ANALYTICS.PRODUCTION_OEE
UNION ALL SELECT 'ASSET_HEALTH_SUMMARY',   COUNT(*) FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_HEALTH_SUMMARY
UNION ALL SELECT 'MAINTENANCE_COST_SUMMARY', COUNT(*) FROM PREDICT_MAINT_DB.ANALYTICS.MAINTENANCE_COST_SUMMARY
ORDER BY ROWS DESC;

-- Expected:
--   ASSET_SENSOR_STATS      172,800
--   PRODUCTION_OEE            8,730
--   ASSET_HEALTH_SUMMARY         30
--   MAINTENANCE_COST_SUMMARY     30

-- 2. Dynamic table health check
SHOW DYNAMIC TABLES IN SCHEMA PREDICT_MAINT_DB.ANALYTICS;
-- Verify scheduling_state = ACTIVE for all 3 DTs

-- 3. Feature completeness (check for NULLs in computed columns)
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(VIB_AVG_24H) AS VIB_AVG_24H_POPULATED,
    COUNT(VIB_STD_24H) AS VIB_STD_24H_POPULATED,
    COUNT(VIB_DELTA_6H) AS VIB_DELTA_6H_POPULATED,
    COUNT(VIB_BASELINE_DEV_PCT) AS VIB_DEV_POPULATED,
    SUM(CASE WHEN VIB_STATUS != 'NORMAL' THEN 1 ELSE 0 END) AS VIB_ALERT_OR_ALARM_ROWS,
    SUM(CASE WHEN TEMP_STATUS != 'NORMAL' THEN 1 ELSE 0 END) AS TEMP_ALERT_OR_ALARM_ROWS
FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_SENSOR_STATS;

-- 4. OEE value ranges (should be between 0 and 1)
SELECT
    ROUND(MIN(OEE), 3) AS MIN_OEE,
    ROUND(AVG(OEE), 3) AS AVG_OEE,
    ROUND(MAX(OEE), 3) AS MAX_OEE,
    ROUND(MIN(AVAILABILITY), 3) AS MIN_AVAIL,
    ROUND(MIN(QUALITY), 3) AS MIN_QUAL
FROM PREDICT_MAINT_DB.ANALYTICS.PRODUCTION_OEE;

-- 5. Health summary spot check (one row per asset, overall status distribution)
SELECT OVERALL_STATUS, COUNT(*) AS ASSET_COUNT
FROM PREDICT_MAINT_DB.ANALYTICS.ASSET_HEALTH_SUMMARY
GROUP BY OVERALL_STATUS;

-- 6. Maintenance cost sanity check
SELECT
    SUM(TOTAL_MAINT_COST_INR) AS TOTAL_COST,
    AVG(MTBF_HOURS) AS AVG_MTBF,
    SUM(CORRECTIVE_COUNT) AS TOTAL_CORRECTIVE_WOS
FROM PREDICT_MAINT_DB.ANALYTICS.MAINTENANCE_COST_SUMMARY;
