-- ============================================================
-- Phase 2: Maintenance Cost Summary
-- Aggregated maintenance costs, MTBF, and spare parts status
-- View | 30 rows (one per asset)
-- ============================================================

USE WAREHOUSE PREDICT_MAINT_WH;
USE SCHEMA PREDICT_MAINT_DB.ANALYTICS;

CREATE OR REPLACE VIEW MAINTENANCE_COST_SUMMARY
AS
WITH wo_agg AS (
    SELECT
        ASSET_ID,
        COUNT(*)                                                        AS TOTAL_WORK_ORDERS,
        SUM(CASE WHEN WO_TYPE = 'CORRECTIVE' THEN 1 ELSE 0 END)       AS CORRECTIVE_COUNT,
        SUM(CASE WHEN WO_TYPE = 'PREVENTIVE' THEN 1 ELSE 0 END)       AS PREVENTIVE_COUNT,
        SUM(CASE WHEN WO_TYPE = 'INSPECTION' THEN 1 ELSE 0 END)       AS INSPECTION_COUNT,
        SUM(CASE WHEN WO_TYPE = 'CORRECTIVE' THEN TOTAL_COST_INR ELSE 0 END)   AS CORRECTIVE_COST_INR,
        SUM(CASE WHEN WO_TYPE = 'PREVENTIVE' THEN TOTAL_COST_INR ELSE 0 END)   AS PREVENTIVE_COST_INR,
        SUM(TOTAL_COST_INR)                                             AS TOTAL_MAINT_COST_INR,
        AVG(CASE WHEN WO_TYPE = 'CORRECTIVE' THEN LABOR_HOURS END)     AS AVG_REPAIR_HOURS,
        AVG(CASE WHEN WO_TYPE = 'CORRECTIVE' THEN WAITING_FOR_PARTS_HOURS END) AS AVG_PARTS_WAIT_HOURS,
        MIN(CREATED_TS)                                                 AS FIRST_WO_TS,
        MAX(CREATED_TS)                                                 AS LAST_WO_TS
    FROM PREDICT_MAINT_DB.RAW.WORK_ORDERS
    GROUP BY ASSET_ID
),
mtbf AS (
    SELECT
        ASSET_ID,
        CASE WHEN COUNT(*) > 1
             THEN DATEDIFF('hour', MIN(CREATED_TS), MAX(CREATED_TS))::FLOAT / (COUNT(*) - 1)
             ELSE NULL END AS MTBF_HOURS
    FROM PREDICT_MAINT_DB.RAW.WORK_ORDERS
    WHERE WO_TYPE = 'CORRECTIVE'
    GROUP BY ASSET_ID
),
parts_stock AS (
    SELECT
        PLANT,
        SUM(CASE WHEN ON_HAND_QTY <= REORDER_POINT THEN 1 ELSE 0 END) AS LOW_STOCK_PARTS,
        COUNT(*) AS TOTAL_PARTS
    FROM PREDICT_MAINT_DB.RAW.SPARE_PARTS
    GROUP BY PLANT
)
SELECT
    a.ASSET_ID,
    a.ASSET_NAME,
    a.ASSET_TYPE,
    a.PLANT,
    a.CRITICALITY,
    a.DOWNTIME_COST_PER_HOUR_INR,
    COALESCE(w.TOTAL_WORK_ORDERS, 0)   AS TOTAL_WORK_ORDERS,
    COALESCE(w.CORRECTIVE_COUNT, 0)    AS CORRECTIVE_COUNT,
    COALESCE(w.PREVENTIVE_COUNT, 0)    AS PREVENTIVE_COUNT,
    COALESCE(w.INSPECTION_COUNT, 0)    AS INSPECTION_COUNT,
    COALESCE(w.CORRECTIVE_COST_INR, 0) AS CORRECTIVE_COST_INR,
    COALESCE(w.PREVENTIVE_COST_INR, 0) AS PREVENTIVE_COST_INR,
    COALESCE(w.TOTAL_MAINT_COST_INR, 0) AS TOTAL_MAINT_COST_INR,
    w.AVG_REPAIR_HOURS,
    w.AVG_PARTS_WAIT_HOURS,
    m.MTBF_HOURS,
    ps.LOW_STOCK_PARTS                  AS PLANT_LOW_STOCK_PARTS,
    ps.TOTAL_PARTS                      AS PLANT_TOTAL_PARTS
FROM PREDICT_MAINT_DB.RAW.ASSETS a
LEFT JOIN wo_agg w ON a.ASSET_ID = w.ASSET_ID
LEFT JOIN mtbf m ON a.ASSET_ID = m.ASSET_ID
LEFT JOIN parts_stock ps ON a.PLANT = ps.PLANT;
